### ISSUE TITLE
Import shared ironing table TEO model

### ISSUE THREAD

**Issue by RaulFdzbis** [roboticslab-uc3m/teo-openrave-models#15]
Import shared TEO models. Not environments, simply objects.
Refs:
- [x] Import https://github.com/roboticslab-uc3m/textiles/pull/61 (used for textiles and xgnitive)
- ~Update https://github.com/roboticslab-uc3m/textiles/tree/b2862bb5ea61d07ea6f3c593fb984a55cb30e3a7/textiles/ironing/manipulation/ironingSim~ -> Should be treated at https://github.com/roboticslab-uc3m/textiles/issues/54
- ~https://github.com/roboticslab-uc3m/xgnitive/issues/54~ -> this is an issue itself

**Comment by jgvictores** [comment]
Blocks https://github.com/roboticslab-uc3m/xgnitive/issues/54

**Comment by jgvictores** [comment]
Closing via https://github.com/roboticslab-uc3m/teo-openrave-models/commit/cc4a86b2b14207aac9b0d0b3fc7d7131868d2ad1 and https://github.com/roboticslab-uc3m/teo-configuration-files/commit/79f6f64d6be315d09795923329b29245ee91f52d

Other issues are open to focues on specific integration and cleanups.
