### ISSUE TITLE
toDo: recalculate inverse-kinematic files with the new limits

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/teo-openrave-models#18]
New value of joint limits changed.
Issue related: https://github.com/roboticslab-uc3m/teo-main/issues/15#issuecomment-366215853

**Comment by rsantos88** [comment]
pending to revise the limits by @jgvictores

**Comment by jgvictores** [comment]
No longer blocked, merged #17

**Comment by jgvictores** [comment]
Blocked by #19

**Comment by jgvictores** [comment]
BTW, did merge rightArmTrunkIk.so into develop/master as part of the cleaning process, for now.
Still blocked by #19.

**Comment by jgvictores** [comment]
No longer required, as of #19, .so are generated by users.
This is included in the install guide: https://github.com/roboticslab-uc3m/teo-openrave-models/blob/0efd49e662495f8ca329ac0089fc37243ab7519c/doc/teo-openrave-models-install.md#generate-openrave-databases
