### ISSUE TITLE
Reorganizing TEO openrave model

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/teo-openrave-models#31]
Following <http://openrave.programmingvision.com/wiki/index.php/Format:XML#Joining_A_Robot_Arm_and_Hand>, we would like:
- [x] A model of TEO without hands/grippers (OpenRAVE robot)
- [x] Models of different TEO hands/grippers (also OpenRAVE robots)
    - [x] Fetch
    - [x] Dextra
- [x] Models that integrate the above
    - [x] TEO + Fetch
    - [x] TEO + Dextra

**Comment by rsantos88** [comment]
Done at https://github.com/roboticslab-uc3m/teo-openrave-models/commit/a27e6b9e8708e52b198ebea80c6d3579b419978d !!!

**Comment by jgvictores** [comment]
PS: `teoSim` was consequently updated at https://github.com/roboticslab-uc3m/teo-configuration-files/commit/548f608f0863936a0cbb3e3d2521c177915837e3
