### ISSUE TITLE
Recover model from `hands-rotated` branch

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/teo-openrave-models#33]
As a followup of #27 and #31, recover model from `hands-rotated` branch:
- https://github.com/roboticslab-uc3m/teo-openrave-models/tree/hands-rotated
- https://github.com/roboticslab-uc3m/teo-openrave-models/tree/25002e22e53ae53cc3981894ce4b789112d60259

**Comment by rsantos88** [comment]
done at https://github.com/roboticslab-uc3m/teo-openrave-models/pull/34

**Comment by jgvictores** [comment]
Merged, thanks!!!
